# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=50)),
                ('acumScore', models.IntegerField(default=0)),
            ],
        ),
    ]
