# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escenario', multiselectfield.db.fields.MultiSelectField(choices=[('WAR', 'Wari'), ('MOC', 'Mochica'), ('PAR', 'Paracas'), ('TIA', 'Tiahuanaco')], max_length=15)),
                ('personaje', multiselectfield.db.fields.MultiSelectField(choices=[(('inwar',), 'Inca Wari'), (('inmoc',), 'Inca Mochica'), (('inpar',), 'Inca Paracas (Mujer)'), (('intia',), 'Inca Tiahuanaco')], max_length=43)),
                ('modo_juego', multiselectfield.db.fields.MultiSelectField(choices=[(('single',), 'Single'), ('arcade', 'Arcade')], max_length=18)),
                ('dificultad', multiselectfield.db.fields.MultiSelectField(choices=[(('normal',), 'Normal'), (('dificil',), 'Dificil'), ('experto', 'Experto')], max_length=32)),
                ('intro_background', models.CharField(choices=[(('https://www-cdn.terminalfour.com/media/sky-night-stars-pexels.jpg',), '1er background'), (('http://www.powerpointhintergrund.com/uploads/2017/05/simple-backgrounds-wallpaper-1920x1080--47273-24.jpeg',), '2do background')], default=('https://www-cdn.terminalfour.com/media/sky-night-stars-pexels.jpg',), max_length=4)),
                ('speed_player', models.IntegerField()),
                ('life', models.IntegerField()),
                ('game_time', models.IntegerField()),
                ('musica', models.CharField(choices=[(('1',), '1er track'), ('2', '2do track')], default=('1',), max_length=4)),
            ],
        ),
    ]
