# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0002_remove_partida_intro_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='dificultad',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('normal', 'Normal'), ('dificil', 'Dificil'), ('experto', 'Experto')], max_length=22),
        ),
        migrations.AlterField(
            model_name='partida',
            name='modo_juego',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('single', 'Single'), ('arcade', 'Arcade')], max_length=13),
        ),
        migrations.AlterField(
            model_name='partida',
            name='musica',
            field=models.CharField(choices=[('1', '1er track'), ('2', '2do track')], default='1', max_length=4),
        ),
        migrations.AlterField(
            model_name='partida',
            name='personaje',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('inwar', 'Inca Wari'), ('inmoc', 'Inca Mochica'), ('inpar', 'Inca Paracas (Mujer)'), ('intia', 'Inca Tiahuanaco')], max_length=23),
        ),
    ]
