# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0004_partida_intro_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='game_time',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='partida',
            name='life',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='partida',
            name='speed_player',
            field=models.IntegerField(default=1),
        ),
    ]
