# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0006_auto_20171126_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='musica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
