# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0007_auto_20171126_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='dificultad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal'), ('dificil', 'Dificil'), ('experto', 'Experto')], max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='escenario',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('WAR', 'Wari'), ('MOC', 'Mochica'), ('PAR', 'Paracas'), ('TIA', 'Tiahuanaco')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='intro_background',
            field=models.CharField(choices=[('https://www-cdn.terminalfour.com/media/sky-night-stars-pexels.jpg', '1er background'), ('http://www.powerpointhintergrund.com/uploads/2017/05/simple-backgrounds-wallpaper-1920x1080--47273-24.jpeg', '2do background')], default='https://www-cdn.terminalfour.com/media/sky-night-stars-pexels.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='partida',
            name='modo_juego',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('single', 'Single'), ('arcade', 'Arcade')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='musica',
            field=models.CharField(choices=[('1', '1er track'), ('2', '2do track')], default='1', max_length=4),
        ),
        migrations.AlterField(
            model_name='partida',
            name='personaje',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('inwar', 'Inca Wari'), ('inmoc', 'Inca Mochica'), ('inpar', 'Inca Paracas (Mujer)'), ('intia', 'Inca Tiahuanaco')], max_length=23, null=True),
        ),
    ]
