# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0008_auto_20171126_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='intro_background',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='musica',
        ),
        migrations.AlterField(
            model_name='partida',
            name='dificultad',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('dificil', 'Dificil'), ('experto', 'Experto')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='escenario',
            field=models.CharField(blank=True, choices=[('WAR', 'Wari'), ('MOC', 'Mochica'), ('PAR', 'Paracas'), ('TIA', 'Tiahuanaco')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='modo_juego',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('arcade', 'Arcade')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='personaje',
            field=models.CharField(blank=True, choices=[('inwar', 'Inca Wari'), ('inmoc', 'Inca Mochica'), ('inpar', 'Inca Paracas (Mujer)'), ('intia', 'Inca Tiahuanaco')], max_length=200, null=True),
        ),
    ]
