# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0009_auto_20171126_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='game_time',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='life',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='speed_player',
        ),
        migrations.AlterField(
            model_name='partida',
            name='dificultad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='escenario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='modo_juego',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='personaje',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
