# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0010_auto_20171126_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='game_time',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='partida',
            name='life',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='partida',
            name='speed_player',
            field=models.IntegerField(default=1),
        ),
    ]
