# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0011_auto_20171126_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='intro_background',
            field=models.CharField(choices=[('https://www-cdn.terminalfour.com/media/sky-night-stars-pexels.jpg', '1er background'), ('http://www.powerpointhintergrund.com/uploads/2017/05/simple-backgrounds-wallpaper-1920x1080--47273-24.jpeg', '2do background')], default='https://www-cdn.terminalfour.com/media/sky-night-stars-pexels.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='partida',
            name='musica',
            field=models.CharField(choices=[('1', '1er track'), ('2', '2do track')], default='1', max_length=4),
        ),
    ]
