# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0014_auto_20171126_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='musica',
            field=models.CharField(choices=[('1', '1er track'), ('2', '2do track')], default='1', max_length=4),
        ),
    ]
