# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 18:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0016_auto_20171126_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='speed_player',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
