# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0018_auto_20171126_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='intro_background',
            field=models.CharField(choices=[('http://res.cloudinary.com/dfktnvqxe/image/upload/v1511719844/escenario_fondo_v2_ikkq4e.jpg', '1er background'), ('http://www.powerpointhintergrund.com/uploads/2017/05/simple-backgrounds-wallpaper-1920x1080--47273-24.jpeg', '2do background')], default='http://res.cloudinary.com/dfktnvqxe/image/upload/v1511719844/escenario_fondo_v2_ikkq4e.jpg', max_length=250),
        ),
    ]
