# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0019_auto_20171126_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='game_time',
        ),
    ]
